multimodal_multistep:
    lr: 0.0005
    max_epoch: 120
    batch_size: 256
    scheduler: "MultiStep"
    scheduler_args:
        milestones: [40]
        gamma: 0.1
    patience: 10
    verbose: False
    visualize: False
    use_wandb: True

multimodal_grid:
    max_epoch: 150
    batch_size: 256
    patience: 10
    verbose: False
    visualize: False
    use_wandb: True

multimodal_multistep_highd:
    lr: 0.0005
    max_epoch: 120
    batch_size: 64
    scheduler: "MultiStep"
    scheduler_args:
        milestones: [40]
        gamma: 0.1
    patience: 10
    verbose: False
    visualize: False
    use_wandb: True
