power-mono-DAG:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [60, 60, 60, 30]
  nb_steps_dual: 30
  l1: 0.
  gumble_T: .5
  normalizer: 'monotonic'
  int_net: [100, 100, 100]
  nb_steps: 20
  solver: 'CC'

power-affine-DAG:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [60, 60, 60, 2]
  nb_steps_dual: 30
  l1: 0.
  gumble_T: .5
  normalizer: 'affine'

power-mono-autoregressive:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [60, 60, 60, 30]
  normalizer: 'monotonic'
  int_net: [100, 100, 100]
  nb_steps: 20
  solver: 'CC'

power-affine-autoregressive:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [60, 60, 60, 2]
  normalizer: 'affine'

power-affine-straf:
  dataset: 'power'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'StrAF'
  emb_net: [60, 60, 60, 2]
  normalizer: 'affine'
#  adjacency_path: './adj_mtx/power_adj_1.npz'
  permutation_path: './adj_mtx/power_perm_1.npz'

gas-affine-straf:
  dataset: 'gas'
  nb_flow: 1
  b_size: 10000
  nb_epoch: 10000
  emb_net: [100, 3]
  normalizer: 'affine'
  weight_decay: 1e-3
  conditioner: 'StrAF'
  permutation_path: './adj_mtx/gas_perm_1.npz'

gas-mono-DAG:
  dataset: 'gas'
  nb_flow: 1
  b_size: 10000
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [80, 80, 80, 30]
  nb_steps_dual: 100
  l1: 0.
  gumble_T: .5
  normalizer: 'monotonic'
  int_net: [200, 200, 200]
  nb_steps: 20
  solver: 'CC'
  weight_decay: 1e-3

gas-affine-DAG:
  dataset: 'gas'
  nb_flow: 1
  b_size: 10000
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [80, 80, 80, 30]
  nb_steps_dual: 100
  l1: 0.
  gumble_T: .5
  normalizer: 'affine'
  weight_decay: 1e-3

gas-mono-coupling:
  dataset: 'gas'
  nb_flow: 1
  b_size: 10000
  nb_epoch: 10000
  conditioner: 'Coupling'
  emb_net: [80, 80, 80, 30]
  normalizer: 'monotonic'
  int_net: [200, 200, 200]
  nb_steps: 20
  solver: 'CC'
  weight_decay: 1e-3

gas-affine-coupling:
  dataset: 'gas'
  nb_flow: 1
  b_size: 10000
  nb_epoch: 10000
  conditioner: 'Coupling'
  emb_net: [80, 80, 80, 30]
  normalizer: 'affine'
  weight_decay: 1e-3

gas-mono-autoregressive:
  dataset: 'gas'
  nb_flow: 1
  b_size: 10000
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [80, 80, 80, 30]
  normalizer: 'monotonic'
  int_net: [200, 200, 200]
  nb_steps: 20
  solver: 'CC'
  weight_decay: 1e-3

gas-affine-autoregressive:
  dataset: 'gas'
  nb_flow: 1
  b_size: 10000
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [80, 80, 80, 30]
  normalizer: 'affine'
  weight_decay: 1e-3

hepmass-mono-DAG:
  dataset: 'hepmass'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [210, 210, 210, 30]
  nb_steps_dual: 25
  l1: 0.
  gumble_T: .5
  normalizer: 'monotonic'
  int_net: [200, 200, 200]
  nb_steps: 20
  solver: 'CCParallel'
  weight_decay: 1e-4

hepmass-affine-DAG:
  dataset: 'hepmass'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [210, 210, 210, 30]
  nb_steps_dual: 25
  l1: 0.
  gumble_T: .5
  normalizer: 'affine'
  weight_decay: 1e-4

hepmass-mono-autoregressive:
  dataset: 'hepmass'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [210, 210, 210, 30]
  normalizer: 'monotonic'
  int_net: [200, 200, 200]
  nb_steps: 20
  solver: 'CCParallel'
  weight_decay: 1e-4

hepmass-affine-autoregressive:
  dataset: 'hepmass'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [210, 210, 210, 30]
  normalizer: 'affine'
  weight_decay: 1e-4

hepmass-affine-straf:
  dataset: 'hepmass'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'StrAF'
  emb_net: [210, 210, 210, 30]
  normalizer: 'affine'
  weight_decay: 1e-4
  adjacency_path: './adj_mtx/hepmass_adj.npz'
  permutation_path: './adj_mtx/hepmass_perm.npz'

miniboone-mono-DAG:
  dataset: 'miniboone'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [430, 430, 430, 30]
  nb_steps_dual: 200
  l1: 0.
  gumble_T: .5
  normalizer: 'monotonic'
  int_net: [40, 40, 40]
  nb_steps: 20
  solver: 'CCParallel'
  weight_decay: 1e-2

miniboone-affine-DAG:
  dataset: 'miniboone'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [430, 430, 430, 30]
  nb_steps_dual: 200
  l1: 0.
  gumble_T: .5
  normalizer: 'affine'
  weight_decay: 1e-2

miniboone-mono-autoregressive:
  dataset: 'miniboone'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [430, 430, 430, 30]
  normalizer: 'monotonic'
  int_net: [40, 40, 40]
  nb_steps: 20
  solver: 'CCParallel'
  weight_decay: 1e-2

miniboone-affine-autoregressive:
  dataset: 'miniboone'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [430, 430, 430, 30]
  normalizer: 'affine'
  weight_decay: 1e-2

bsds300-mono-DAG:
  dataset: 'bsds300'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [630, 630, 630, 30]
  nb_steps_dual: 20
  l1: 0.
  gumble_T: .5
  normalizer: 'monotonic'
  int_net: [150, 150, 150]
  nb_steps: 20
  solver: 'CCParallel'
  weight_decay: 1e-4

bsds300-affine-DAG:
  dataset: 'bsds300'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [630, 630, 630, 30]
  nb_steps_dual: 20
  l1: 0.
  gumble_T: .5
  normalizer: 'affine'
  weight_decay: 1e-4

bsds300-mono-autoregressive:
  dataset: 'bsds300'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [630, 630, 630, 30]
  normalizer: 'monotonic'
  int_net: [150, 150, 150]
  nb_steps: 20
  solver: 'CCParallel'
  weight_decay: 1e-4

bsds300-affine-autoregressive:
  dataset: 'bsds300'
  nb_flow: 1
  b_size: 100
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [630, 630, 630, 30]
  normalizer: 'affine'
  weight_decay: 1e-4

gaussian_prev_2_d20-affine-autoregressive:
  dataset: 'gaussian_prev_2_d20'
  nb_flow: 1
  b_size: 200
  nb_epoch: 10000
  conditioner: 'Autoregressive'
  emb_net: [100, 2]
  normalizer: 'affine'

gaussian_prev_2_d20-affine-DAG:
  dataset: 'gaussian_prev_2_d20'
  nb_flow: 1
  b_size: 200
  nb_epoch: 10000
  conditioner: 'DAG'
  emb_net: [100, 2]
  nb_steps_dual: 30
  l1: 0.
  gumble_T: .5
  normalizer: 'affine'
  adjacency_path: './adj_mtx/prev_2_d20_adj.npz'

gaussian_prev_2_d20-affine-straf:
  dataset: 'gaussian_prev_2_d20'
  nb_flow: 1
  b_size: 2500
  nb_epoch: 10000
  conditioner: 'StrAF'
  emb_net: [100, 2]
  normalizer: 'affine'
  adjacency_path: './adj_mtx/prev_2_d20_adj.npz'
